### ISSUE TITLE
Can't exclude specific files

### ISSUE THREAD

**Issue by obregonia1** [r7kamura/slimcop#7]
I created `.silmcop.yml` like below  in root of repository and then execute `$ bundle exec slimcop --config .slimcop.yml`. But slimcop inspects files even though I ruled it out. Is there any solution or I did wrong way?
```yaml
inherit_from: .rubocop.yml

Rails/OutputSafety:
  Enabled: false

AllCops:
  Exclude:
    - app/views/**/*
```
