### ISSUE TITLE
False negative on Slim's text interpolation syntax?

### ISSUE THREAD

**Issue by neko314** [r7kamura/slimcop#8]
`Layout/SpaceInsideStringInterpolation` is enable by default on RuboCop. (See: https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsidestringinterpolation).
I expect slimcop to find offending codes but it doesn't. RuboCop finds offense in anything but views (like models) so I think there is something wrong with slimcop or templatecop but I'm not sure🤔

## Step to reproduce

```yml
# rubocop.yml
# no matter if I specify configuration or not. just example below
Layout/SpaceInsideStringInterpolation
  enable: true
  EnforcedStyle: no_space
```

```
# app/views/sample.html.slim 
- name = "name"
= "#{ name }"
```

and run checking

```
slimcop "app/views/sample.html.slim"
```

## Expected result

```
app/views/sample.html.slim:n:n C: Layout/SpaceInsideStringInterpolation: Space inside string interpolation detected.
```

## Actual result

```
1 file inspected, no offenses detected
```
